version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=pawmatch;Username=postgres;Password=mandaci12
      - GoogleDrive__CredentialsPath=/app/credentials/credentials.json
    volumes:
      - ./credentials:/app/credentials
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "dotnet", "PawMatch.Api.dll"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=pawmatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mandaci12
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
      

volumes:
  db-data:
