version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=pawmatch;Username=postgres;Password=mandaci12
      - GoogleDrive__CredentialsPath=/app/credentials/credentials.json
    volumes:
      - ./credentials:/app/credentials
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "dotnet", "PawMatch.Api.dll"]

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pawmatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mandaci12
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
  caddy_data:
  caddy_config:
